### ISSUE TITLE
How to install with VuePress?

### ISSUE THREAD

**Issue by soucat** [KnowsCount/portfolio#6]
This is a beautiful project! I'd love to fork and modify for my own project! ❤️ 
But how can I actually install it?
Thanks!

**Comment by KnowsCount** [comment]
what do you mean by install?
You can simply run `npm install` in the repository and run `npm run dev` to start the project in developement view..
If you want to build, run `npm build`.
I used Vercel to deploy.

**Comment by KnowsCount** [comment]
I'll close this for now.
